steps:
- name: "gcr.io/cloud-builders/docker"
args: ["build", "-t", "gcr.io/cloudrun-327419/angular8application", "-f", "./Dockerfile", "."]
- name: "gcr.io/cloud-builders/docker"
args: ["push", "gcr.io/cloudrun-327419/angular8-application"]
- name: "gcr.io/cloud-builders/gcloud"
args:
[
"run",
"deploy",
"--allow-unauthenticated",
"cloudrun-327419",
"--image",
"gcr.io/cloudrun-327419/angular8-application",
"--region",
"us-central1",
"--platform",
"managed",
"--memory",
"128Mi"
]
images:
- gcr.io/cloudrun-327419/angular8-application